name: Increment Package Version

# on:
#   pull_request:
#     types: [closed]
#     branches:
#       - main

on:
  push:
    branches:
      - "actions"

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Increment Version
        run: cd stencil-lib && npm version minor -m "Bump version to %s [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}